services:
  alice:
    build:
      context: ../
      dockerfile: memo-dwa-demo/Dockerfile.alice
    ports:
      - "3000:5173"
  bob:
    build:
      context: ../
      dockerfile: memo-dwa-demo/Dockerfile.bob
    ports:
      - "4000:5173"
