FROM node:20.11.1-slim

WORKDIR /app
COPY package.json yarn.lock ./
RUN chown -R node:node ./

USER node
RUN yarn install --frozen-lockfile && yarn cache clean

COPY . .
COPY ./memo-dwa-demo/alice/.env.dev .
EXPOSE 3000
CMD ["yarn", "dev"]